apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: scalpel
build:
  artifacts:
  - image: ghcr.io/gleeds/scalpel-api
    context: ./src
    docker:
      cacheFrom:
        - scalpel-api
      dockerfile: ./src/Dockerfile
    sync:
      manual:
        - src: .
          dest: /usr/src/app    
  - image: ghcr.io/gleeds/scalpel-ui
    context: ./ui
    docker:
      # cacheFrom:
      #   - scalpel-ui
      dockerfile: ./ui/Dockerfile
    sync:
      # manual:
      #   - src: ./ui
      #     dest: /usr/src/app   
      infer:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.css'
  - image: demo-mysql
    docker:
      cacheFrom:
        - demo-mysql
      dockerfile: ./demo-mysql/Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*
