apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: scalpel
build:
  artifacts:
  - image: scalpel-api
    docker:
      cacheFrom:
        - scalpel-api
      dockerfile: ./Dockerfile
    sync:
      manual:
        - src: ./src
          dest: /usr/src/app
      
  - image: demo-mysql
    docker:
      cacheFrom:
        - demo-mysql
      dockerfile: ./demo-mysql/Dockerfile


deploy:
  kubectl:
    manifests:
    - k8s/*
