apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-mysql
  name: demo-mysql
spec:
  selector:
    app: demo-mysql
  ports:
    - port: 3306
      name: mysql
      targetPort: 3306
  type: LoadBalancer