apiVersion: v1
kind: Service
metadata:
  labels:
    app: scalpel-api
  name: scalpel-api
spec:
  selector:
    app: scalpel-api
  ports:
    - port: 3000
      name: http
      targetPort: 3000
  type: LoadBalancer